name: New Story
description: Create a new story
title: "[Story]: "
labels: [story]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a new story to improve our product!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: The user story for the feature.
      placeholder: As a user, I would like to ... so I can ...
    validations:
      required: true
  - type: textarea
    id: ux
    attributes:
      label: UX
      description: Design of the feature. If no design is available leave questions for UX here.
      placeholder: Implement the following design...
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: The criteria for which the story will be accepted in a Pull Request.
      placeholder: The implementation should have ...
    validations:
      required: true
  - type: textarea
    id: comments-questions
    attributes:
      label: Comments / questions
      description: Any comments or questions relating the story.
      placeholder: Should we devide this into sub-tasks?
  - type: textarea
    id: DOR/DOD
    attributes:
      label: Definition of ready/done
      description: This field is not to be changed!
      value: |
        - [ ] Definition of ready
        <details>
        <summary>DOR</summary>

        - Acceptance criteria written and reviewed by QA, PM and SE
        - Behaviour scenarios written
        - Signed off UX design
        - Estimated and appropriately scoped

        </details>

        - [ ] Definition of done
        <details>
        <summary>DOR</summary>

        - Test complete
            - Merged to master
            - Unit tests on all new code (80% coverage)
            - Integration tests for endpoints / web sockets
            - End-to-end or integration tests verifying acceptance criteria
        - Code complete
            - Peer reviewed (2 people)
            - Follows Helpful code standards / versioning guidelines
            - No commented out code or TODOs
            - TSLint / Sonarqube exceptions have explicit explanations
        - Verified by QA
            - Functionally manually verified on a setup like the actual setup
            - QA verifies test coverage aligns with master test plan
        - Verified by UX and product owner / verified by the team
        - Documentation of tech debt
        - Persistent technical documentation updated / written
            - Ready is updated / written

        </details>
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
